# Generated by Django 2.2.4 on 2019-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da ong')),
                ('responsavel', models.CharField(max_length=50, verbose_name='responsavel')),
                ('endereco', models.DateField(verbose_name='Endereco')),
                ('telefone', models.CharField(max_length=255, unique=True, verbose_name='telefone')),
                ('horario', models.CharField(max_length=10, verbose_name='horario')),
                ('observacao', models.CharField(max_length=5, verbose_name='observao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
