# Generated by Django 2.2.4 on 2019-08-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='observacao',
            field=models.CharField(max_length=255, verbose_name='observacao'),
        ),
    ]
