# Generated by Django 2.2.4 on 2019-08-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190830_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='ong',
            name='telefone',
            field=models.CharField(max_length=255, verbose_name='telefone'),
        ),
    ]
